name: vue-ellipsis-component-doc
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - tongji
    paths-ignore: # 下列文件的变更不触发部署
      - packages/*
      - public/*
      - test/*
      - demo/*
      - build/*
      - README.md
      - LICENSE
      - .browserslistrc
      - .gitignore
      - babel.config.js
      - tsconfig.json
      - .eslintrc.js
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout # 1. 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v2
    - name: Install Node
      run: yarn global add n && sudo n 16.17.1
    - name: Install # 2. 安装依赖
      run: yarn config set registry https://registry.npmjs.org/ && yarn
    - name: Build   # 3. 打包
      run: yarn docs:build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: '-avz --delete --exclude *.js.map'
          SOURCE: './docs/.vuepress/dist'
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.PATH }}